INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.openweathermap.org
DEBUG:requests.packages.urllib3.connectionpool:"GET /data/2.5/weather?q=Bayon,fr&units=metric HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 193.55.104.132
DEBUG:requests.packages.urllib3.connectionpool:"POST /db/Loumanolkar/series?p=root&time_precision=s&u=root HTTP/1.1" 200 0
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ap.openweathermap.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ap.openweathermap.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ap.openweathermap.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ap.openweathermap.org
ERROR:root:HTTPConnectionPool(host='ap.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?q=Bayon,fr&units=metric (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ap.openweathermap.org
ERROR:root:HTTPConnectionPool(host='ap.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?q=Bayon,fr&units=metric (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
